WEB_PROYECTOS/Controllers/DepartamentoController.cs
using ENTIDAD;
using NEGOCIO;
using System;
using System.Net;
using System.Web.Mvc;

namespace WEB_PROYECTOS.Controllers
{
    public class DepartamentoController : Controller
    {
        // GET: Departamento esto es lo mismo que tener [HttpGet] (al no ponerlo, se entiende que es Get)
        public ActionResult Index()
        {
            var datos = DepartamentoCN.ListarDepartamentos();
            return View(datos);
        }

        [HttpGet] // Solicitar información del servidor
        public ActionResult Crear()
        {
            return View();
        }

        [HttpPost] // Cuando envío información desde el cliente al servidor
        [ValidateAntiForgeryToken]
        public ActionResult Crear(Departamento departamento)
        {
            try
            {
                DepartamentoCN.Agregar(departamento);
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Ocurrió un error al Agregar un Departamento");
                return View(departamento);
            }   
        }

        public ActionResult Detail(int id)
        {
            var depertamento = DepartamentoCN.Detail(id);
            return View(depertamento);
        }

        public ActionResult Editar(int id)
        {
            var departamento = DepartamentoCN.Detail(id);
            return View(departamento);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(Departamento departamento)
        {
            try
            {
                DepartamentoCN.Editar(departamento);
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Ocurrió un error al Editar el Departamento");
                return View(departamento);
            }
        }

        public ActionResult Eliminar(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);

            var departamento = DepartamentoCN.Detail(id.Value);
            return View(departamento);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Eliminar(int id)
        {
            try
            {
                DepartamentoCN.Eliminar(id);
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Ocurrió un error al Eliminar el Departamento");
                return View(); // retornar la misma vista
            }
        }

    }
}

WEB_PROYECTOS/Controllers/ProyectoController.cs
using ENTIDAD;
using NEGOCIO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WEB_PROYECTOS.Controllers
{
    public class ProyectoController : Controller
    {
        // GET: Proyecto
        public ActionResult Index()
        {
            var proyectos = ProyectoCN.ListarProyectos();
            return View(proyectos);
        }

        public ActionResult Crear()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Crear(Proyecto proyecto)
        {
            try
            {
                if(proyecto.NombreProyecto == null)
                    return Json(new { ok = false, toRedirect = "Debe ingresar el nombre del proyecto" }, JsonRequestBehavior.AllowGet);

                ProyectoCN.Agregar(proyecto);
                return Json(new { ok = true, toRedirect = "Index" }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { ok = false, msj = ex.Message }, JsonRequestBehavior.AllowGet);
                //ModelState.AddModelError("", "Ocurrió un error al agregar un Proyecto");
                //return View();

            }
        }




    }
}

WEB_PROYECTOS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @*<link rel="stylesheet" href="https://cdn.dhtmlx.com/edge/dhtmlx.css" type="text/css">*@
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Proyectos WEB", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <!-- Texto, Acción, Controlador  -->
                    <li>@Html.ActionLink("Inicio", "Index", "Home")</li>
                    <li>@Html.ActionLink("Departamentos", "Index", "Departamento")</li>
                    <li>@Html.ActionLink("Proyectos", "Index", "Proyecto")</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer id="footer">
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
    @*<script src="https://cdn.dhtmlx.com/edge/dhtmlx.js" type="text/javascript"></script>.
    <script src="~/javascript/index.js"></script>*@

    <script>
        $(document).ready(function () {
        /*    console.log("Prueba");*/
            //var myWins = new dhtmlXWindows();
           
            //var win = myWins.createWindow("Ventana1", 1, 200, 1150, 800);

            //myWins.window("Ventana1").setText("Proyectos WEB");

            //myWins.window("Ventana1").denyResize();

            //myWins.window("Ventana1").attachURL("https://localhost:44393/");

        });



    </script>
</body>
</html>